# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '动画' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 动画

  target '动画Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '动画UITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
pod 'lottie-ios'  ,'~>2.5.0'
pod 'IQKeyboardManager' ,'~>6.0.4'
pod 'GTMBase64' ,'~>1.0.1'
pod 'MBProgressHUD', '~> 1.1.0'

end
